name: Review

on: [pull_request]

jobs:
  review:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: reviewdog/action-staticcheck@v1
      with:
        fail_on_error: true
