name: Security scanning

on:
  pull_request:
    branches:
    - '*'
  workflow_dispatch: {}

jobs:
  secscan:
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: on
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Security scanning
      uses: securego/gosec@master
      with:
        args: ./...
