name: Run Tests

on:
  pull_request:
    branches:
    - '*'
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Run vet
      run: go vet ./...
    - name: Security scanning
      uses: securego/gosec@master
        with:
          args: ./...
    - name: Run tests
      run: go test -race -v -coverprofile cov.out ./...
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
